### ISSUE TITLE
Assignment 1

### ISSUE THREAD

**Issue by beneyal** [SaarSch/Texas_Holdem#54]
I went over your domain layer code, here are some "issues" I'd like to point out. I'm not saying "fix those fuckers right now", but keep them in the back of your head, so they won't bite you in the ass later.

* You implemented your own logger. Why not use an existing library and save the headache?

* `FindGames` method in `GameManager.cs` needs some serious work. When you see a big-ass conditional like that, those are many small objects screaming "refactor me!". I do see the list of predicates, so you're on the right track. By the way, `FindGames` has very low test coverage.

* `GamePreferences.cs` can be shortened by using auto-implemented properties [[1]](https://docs.microsoft.com/en-us/dotnet/articles/csharp/programming-guide/classes-and-structs/auto-implemented-properties)

* Your `Pair` class is already built-in .NET [[2]](https://msdn.microsoft.com/en-us/library/system.valuetuple(v=vs.110).aspx)

* The `GameCenter` class is doing too much. Go over it, try to categorize the different methods by their responsibility, and refactor those responsibilities to new classes.

* Hebrew comments in `Card.cs` 💩 

* You can't implement a card shuffling algorithm without, at least, knowing about [[3]](https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle)

* `Room.cs` should concern you. I didn't even go through most of it. It's almost 1,000 lines, and the methods are long as fuck. Make sure you have 100% test coverage on that file, and start refactoring. You might end up with 10 new classes, but you'll thank yourselves later. Remember: small classes, short methods, Single Responsibility Principle, and Open/Closed Principle.

That's all for now. See you next Wednesday :shipit:

**Comment by margalda** [comment]
covered the issues. some details:
split Room to Room and HandLogic
split GameCenter to GameCenter UserLogic and MessageLogic
changed to properties in GamePreferences but removed Decorator pattern
changed Pair to Tuple (.NET)
